### ISSUE TITLE
Tact Docs integration

### ISSUE THREAD

**Issue by anton-trunov** [nujan-io/nujan-ide#95]
Web IDE should support getting source code from the Tact docs. For instance, runnable code snippets from the Tact docs can be presented as small contracts with getters.

cc @novusnota for further discussion and shaping this proposal

**Comment by novusnota** [comment]
Like, to add "Run this code in Nujan" kind of text/button to all the doc snippets, then introduce some way of creating new contracts in Nujan via a GET (100% possible) or POST (may be possible) request and lead people via that?

**Comment by anton-trunov** [comment]
Yeah, something like that

**Comment by rahulyadav-57** [comment]
With the new file system I'm working on, this can be easily achieved. The doc will be having a small snippet that can be inserted as a base64 code in URL.
https://ide.nujan.io/?code=base64OfSnippet

Since users might click on multiple `try code` snippets, we can store them in an in-memory file system with an option to save them permanently. This approach will help keep the workspace/project list clean.

Later on once we have a support of git and any other cloud storage for files. We can provide an option to embed it similar to codepen. So user don't have to switch new tab.
